version: '3'
services:
  php:
    build: . # Build avec le Dockerfile
    image: php:7.4.13-apache
    depends_on:
      - mysql
    # Changement du répertoire courant
    working_dir: /var/www/html/crypto-compta
    volumes:
      - .:/var/www/html/crypto-compta
    # Définition du port sur lequel écouté, on le lie au port 8080 local "portchoisi:portapache"
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      # Variables d'environnement pour se connecter à la base de données
      - MYSQL_DATABASE=cryptocompta
      - MYSQL_ROOT_PASSWORD=mQOla?lfp!5PFYNA15xf3
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_name
    restart: always
    ports:
      - '8088:80'
    environment:
      PMA_HOST: mysql

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
